---
title: "Introduction: The Effect of Geographical Awareness Dispersion Through Technology on American Pop Culture"
bibliography: reference.bib
---


Awareness of other parts of the world has developed as the prevalence of daily technological usage continues to grow. While previously displayed primarily through specific cable network channels, discovering new travel and international cuisine content on social media applications and streaming platforms is now an expectation as a consumer of technology. The phenomena of technology being a catalyst for the noticeable evolution of accurate geographical awareness holds several implications for readers.

With the growth in international colloquial adoption, has come the subsequent growth in intercultural appreciation. One paper pointed out how international students, “can also easily teach their English-speaking classmates about their own native language through the translators” (@macfarlane2011different). Translators are a direct technological tool for closing cultural gaps. As sharing cultural information with those around you is a common way people establish connections, technological advances help to further deepen those connections.

Whereas from an external point of view, technological advances that keep the communicative diversity of their audience in mind appear to offer better opportunities for language gaps to be minimized.  A study examining Chinese students in China who attempted to learn colloquialisms through paper content or WeChat observed mobile devices offer, “functions (such as instant chatting, dictionary, or translation) to help learners resolve questions encountered in self-learning”(@yang2018learning). This observation refers to the vast accessibility many technological platforms provide. One direct reflection of this would be streaming platform’s multilingual closed captioning providing viewers with more international– an otherwise excluded– content at their disposal.

I want to explore this phenomena as it pertains to popular culture in the United States of America. I hypothesize the rise of international content being consumed through streaming platforms and the rise in the incorporation of international colloquialisms will yield a positive correlation. Through my research, I hope to address some topics such as:
- What is currently the most influential streaming service on the specific jargon adoption? 
- Which regions seem to currently have the largest influence on colloquialism in American popular culture? 
- How can my findings be utilized to further improve inclusivity through more accurate and widespread adoption?

With that said, the prioritization of international awareness when incorporating methods, such as natural language processing, is already evident. For example, many chatbots are able to communicate in Nigerian pidgin once requested. Also, Apple’s renowned digital assistant, Siri, has the ability to define and use colloquialisms from the United Kingdom upon request. Moreover, through this research, I hope to shed light on the current effects of such tools and highlight focal points for precise innovation.


### Questions:
- Examples of American pop culture colloquialisms? OR Example of adopted pop culture colloquialisms?
- What regions in the United States have more of an effect on shared national colloquialisms?
- What regions globally have more of an effect on shared national colloquialisms (limited to seven continents)?
- Is there a specific age group who is more impressionable to imported jargon?
- Is there a specific region who is more impressionable to imported jargon?
- Largest language dispersion channel (like Netflix, Hulu, Amazon Prime, Apple TV)?
- Is genre influential on how adaptable the terms are?
- Does positive or negative content have more of an effect on adapted jargon?
- Practical applications for encouraging international colloquialisms dispersal?
- How can these applications adapt to the growth of international colloquialisms in America?
