---
title: "Mood, Music, and Media"
bibliography: reference.bib
---


As the prevalence of daily technological usage grows, streaming platforms continue to permeate the infrastructure of societal pastimes. Music streaming platforms such as Apple Music and Spotify, as well as streaming services such as Hulu and Netflix, are becoming increasingly popular due to providing a plethora of entertainment at one’s fingertips. Due to this distinctive growth in an array of highly- accessible media, a desire to cater to individual consumers– and a desire by consumers to be presented with more specialized content– is also increasing. Inspired by works already implemented, my project aims to examine if the self- reported happiness level of a person in the past- year will have a significant impact on their media consumption preferences today.

### Media

Media consumption being tied to emotional state is not a new topic. One study in 1988 used factor analysis on a group of one hundred American students attending university to gauge their reasons for attending movie theaters and the preferences for the movies they watch. The three main reasons consisted of intentional escapism, desires of self improvement, and genuine entertainment. However, even more insightful, was the researchers being able to make out that the movie theater attendees who went for escapism, “preferred movies with an air of unreality” (@doi:10.1080/00223980.1988.10542949). This illustrates how consumers desire to see a part of themselves– or a part they hope to gain– in the various things they consume. 

Taking a more comprehensive approach to present a complementary notion, a more recent study explores how instrumental considering the emotional state of the consumer is to media recommendation. Winoto and Yang (2010) had seventy- seven college students in the midst of final exams’ season participate in their experiment, where they answered questions revolving around 46 movies and 16 sentiment labels. This study yielded insights such as possessing positive- affect and negative- affect have a significant effect on the rating of romantic- comedy movies. Another takeaway is the observation that user recommendation systems may not be as successful when the said user is, “not in the mood to enjoy a movie” (@WINOTO20106086). Taking into account physical exhaustion levels and general mood, the study demonstrates just a fraction of how specific the external and internal influences can be on increasing the bias which affects media consumption preferences.
 
### Music

When specifically looking at music and emotions, one study captures an insight that brings light to how a bias in music preference may be perceived. Taylor and Friedman (2014) analyzed 44 college students’ music preferences after causing them to be in a dejected mood. As a result of the study, the researchers came to the conclusion that people in sadder moods may be expected to avoid, “songs that express happiness” (@doi:10.1080/15213269.2013.826589). This study looked directly at the possible trajectory of music tone choice when sadness is induced, further supporting the possibility of a significant relationship between personal sentiment and music and media preferences.

On the other side of the general analyses presented, one study examined how to detect general moods present in music. Lu, et al. (2005) take features that convey a music piece’s energy, contrast, and rhythm to track the moods in a song. One significant result is the detection method achieving an average accuracy level of 86 percent. When considering the effect of situational emotion arousal, extensive methods such as the one examined here provides researchers with more flexible recommendations.

The phenomena of streaming service preferences being linked to psychological standing holds several implications for readers. One being businesses need to progress in their depth of understanding the multiple facets of consumerism. With more and more platforms competing for customers– such as Spotify vs. Apple Music vs. Pandora and Netflix vs. Hulu vs. Peacock– persistent efforts to create gradually more adaptable recommendation systems is worth exploring.

Another implication being the benefits of consumers becoming more educated on how the entertainment they consume may affect them. As seen in the referenced works, there are a diverse array of effects on various moods to expect from different genres of media and their corresponding sentiments. It may hold significance for many consumers to educate themselves on the directions to take in the entertainment realm to enhance their well- being by encouraging an environment of consumption more conducive to their mental state.

## Project

As an attempt to build on these efforts, my project utilizes algorithms such as Naive Bayes Classifier and Decision Trees to examine what conclusions can be drawn from the level of international subjective satisfaction and worldwide media preferences. In my project, I plan to address questions such as:

- Is there a strong preference for negative content worldwide?
- Is there a strong preference for positive or neutral content worldwide?
- What songs are more likely to be preferred by which countries?
- 

