---
title: "R Equivalent Project"
author: "Ofure Udabor""
embed-resources: True
knit: reprex::reprex_render
---

Apple Top International

```{r}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("dplyr")
library("tibble")

setwd("C:/Users/Amand/OneDrive/Documents/DSAN 5000/website-template/HW1_5000/dsan-5000-project-aou27/websitedata")
apple_Dfr <- read_csv("appletopsongsinternational2023.csv")
apple_Tibble <- as_tibble(apple_Dfr)

apple_Tibble <- apple_Tibble %>%
  pivot_longer(cols = c(-"Pos", -"P+", -"Artist and Title", -"Days",
  -"Pk", -"(x?)", -"Pts", -"Pts+", -"TPts"), names_to = "country", values_to = "country_rank")

apple_Tibble <- apple_Tibble %>%
  select(-"P+", -"Pts+", -"TPts")

colnames(apple_Tibble) <- c("Chart Position", "Artist and Title", "Position Duration", 
"Peak", "(x?)", "Points", "Country", "Country Rank")

apple_Tibble$"(x?)" <- gsub("[^0-9]", "", apple_Tibble$"(x?)")

apple_Tibble<- na.omit(apple_Tibble)


#print(colSums(is.na(apple_Tibble))) #check missing values
dim(apple_Tibble)
head(apple_Tibble)
#write.csv(apple_Tibble, "apple_R.csv")
```

Spotify Artists

```{r}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("dplyr")
library("tibble")

setwd("C:/Users/Amand/OneDrive/Documents/DSAN 5000/website-template/HW1_5000/dsan-5000-project-aou27/websitedata")
spotify_Dfr <- read_csv("Spotify.csv")
spotify_Tibble <- as_tibble(spotify_Dfr)

colnames(spotify_Tibble) <- c("Index", "Artist Name", "Valence", "Danceability", "Energy", "Loudness", "Speechiness", "Acousticness", "Liveness", "Tempo", "Track Name", "Album Name", "Album Release Year")

spotify_Tibble <- spotify_Tibble %>%
  select(c("Index", "Artist Name", "Valence", "Danceability", "Energy", "Loudness", "Speechiness", "Tempo", "Track Name", "Album Name", "Album Release Year"))

head(spotify_Tibble)
dim(spotify_Tibble)
#write.csv(spotify_Tibble, "spotify_R.csv")

```



Netflix Top International

```{r}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("dplyr")
library("tibble")

setwd("C:/Users/Amand/OneDrive/Documents/DSAN 5000/website-template/HW1_5000/dsan-5000-project-aou27/websitedata")
netflix_Dfr <- read_csv("netflixWorld2022.csv")
netflix_Tibble <- as_tibble(netflix_Dfr)

colnames(netflix_Tibble) <- c("Title", "Points")

netflix_Tibble <- netflix_Tibble[-c(1, 2), ]

#print(sum(is.na(netflix_Tibble))) for missing values
dim(netflix_Tibble)
head(netflix_Tibble)
#write.csv(netflix_Tibble, "netflix_R.csv")

```

Self- Reported Happiness

```{r}
setwd("C:/Users/Amand/OneDrive/Documents/DSAN 5000/website-template/HW1_5000/dsan-5000-project-aou27/websitedata")
happy_Dfr <- read_csv("gdp-vs-happiness.csv")

happy_Tibble <- as_tibble(happy_Dfr)
happy_Tibble<- happy_Tibble[happy_Tibble$"Year" == 2022,]

happy_Tibble <- happy_Tibble %>%
  select(c("Entity", "Code", "Cantril ladder score"))

colnames(happy_Tibble) <- c("Entity", "Code", "Score")

#print(sum(is.na(happy_Tibble))) for missing values
dim(happy_Tibble)
head(happy_Tibble)
#write.csv(happy_Tibble, "happy_R.csv")

```
